In [1]:
import sys
import os

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from scipy import stats

# My packages
sys.path.insert(0, "../scs/")
import data_degrading as dd
import data_preparation as dp
import data_augmentation as da
from prepare_datasets_for_training import extract
import data_plotting as dplt
import scs_config

from icecream import ic

from importlib import reload

rng = np.random.RandomState(1415)

In [2]:
df_P_trn = pd.read_parquet("/home/2649/repos/SCS/data/full_res/preprocessed_trn_set.parquet")
df_P_tst = pd.read_parquet("/home/2649/repos/SCS/data/full_res/preprocessed_tst_set.parquet")

In [3]:
ic("Data augmentation.")
wvl_range = (4500, 7000)
spike_scale = 3
max_spikes = 5

df_PA_trn = da.augment(
    df_P_trn,
    rng,
    wvl_range=wvl_range,
    noise_scale=0,
    spike_scale=spike_scale,
    max_spikes=max_spikes,
)

ic| 'Data augmentation.'


In [8]:
num_spec_trn = df_P_trn.shape[0]
trn_amts = df_P_trn.groupby(by=["SN Subtype ID"]).count()["SN Subtype"].values
trn_probs = trn_amts / num_spec_trn
trn_amts, trn_probs

(array([1058,  163,  101,   12,   28,   79,   99,    9,  140,    5,  112,
         118,    6,   58,    4,   19]),
 array([0.52610641, 0.0810542 , 0.05022377, 0.00596718, 0.01392342,
        0.03928394, 0.04922924, 0.00447539, 0.06961711, 0.00248633,
        0.05569368, 0.05867727, 0.00298359, 0.02884137, 0.00198906,
        0.00944804]))

In [5]:
num_spec_tst = df_P_tst.shape[0]
tst_amts = df_P_tst.groupby(by=["SN Subtype ID"]).count()["SN Subtype"].values
tst_probs = tst_amts / num_spec_tst
tst_amts, tst_probs

(array([1056,  185,  131,    4,   34,   32,  112,   18,   93,    7,   94,
         111,   25,   46,    6,    3]),
 array([0.53960143, 0.09453245, 0.06693919, 0.00204394, 0.01737353,
        0.01635156, 0.05723045, 0.00919775, 0.04752172, 0.0035769 ,
        0.0480327 , 0.05671947, 0.01277466, 0.02350537, 0.00306592,
        0.00153296]))

In [6]:
np.dot(trn_probs, tst_probs)

0.06221531678567441